### PR TITLE
Fix message sen on file upload

### LINKED ISSUE #70: Update MQ
Set the MQ message to the expected format:

`{
  "operation": "upload",
  "user": "dummy",
  "filepath": "some/path",
  "filesize": 1234,
  "encrypted_checksums": [
    {"md5": "123az"}
  ]
}`

### PR DESCRIPTION
**Pull request by jbygdell**
Even though sha256 is preferred the backend only gives us MD5 so that's what we have to work with.
Fixes #70

### CODE REVIEW

File: proxy.go [hunk 1]
```diff
@@ -280,7 +280,7 @@ func (p *Proxy) CreateMessageFromRequest(r *http.Request) (Event, error) {
 	}
 	event.Filepath = r.URL.Path
 	event.Username = username
-	checksum.Type = "etag"
+	checksum.Type = "MD5"
```
Comment (viklund) [inline proxy.go:283]:
```suggestion
	checksum.Type = "md5"
```

File: messenger.go [hunk 2]
```diff
@@ -22,7 +22,7 @@ type Event struct {
 	Username  string   `json:"user"`
 	Filepath  string   `json:"filepath"`
 	Filesize  int64    `json:"filesize"`
-	Checksum  Checksum `json:"encoded_checksum"`
+	Checksum  Checksum `json:"encrypted_checksums"`
```
Comment (viklund) [inline messenger.go:25]: This should be a list.

Comment (jbygdell) [reply messenger.go]: `{
    "operation": "upload",
    "user": "username",
    "filepath": "/inbox/file",
    "filesize": 1234,
    "encrypted_checksums": [
        {
            "type": "md5",
            "value": "123qweasdzxc"
        }
    ]
}`
